/*
SQLyog Community v13.1.8 (64 bit)
MySQL - 10.4.21-MariaDB : Database - votaciones
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`votaciones` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci */;

USE `votaciones`;

/*Table structure for table `categoria` */

DROP TABLE IF EXISTS `categoria`;

CREATE TABLE `categoria` (
  `idcategoria` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) COLLATE utf8_spanish2_ci NOT NULL,
  `descripcion` varchar(256) COLLATE utf8_spanish2_ci DEFAULT NULL,
  `condicion` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `categoria` */

insert  into `categoria`(`idcategoria`,`nombre`,`descripcion`,`condicion`) values 
(1,'Categoria Prueba1_1','Prueba 1 Categoria',0);

/*Table structure for table `def_departamentos` */

DROP TABLE IF EXISTS `def_departamentos`;

CREATE TABLE `def_departamentos` (
  `depa_depa` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria de los departamentos',
  `depa_cod_dane` varchar(10) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Codigo dane del departamernto',
  `depa_pais` int(11) NOT NULL COMMENT 'Pais al que pertenece el departamento',
  `depa_descri` varchar(50) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Descripci',
  `depa_estado` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Estado del departamento A Activo I Inactivo',
  `depa_usuains` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario inserta',
  `depa_fecins` date DEFAULT NULL COMMENT 'Fecha Inserta',
  `depa_usuaupd` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario actualiza',
  `depa_fechaupd` date DEFAULT NULL COMMENT 'fecha_actualiza',
  PRIMARY KEY (`depa_depa`) COMMENT 'Llave primaria def_departamentos',
  UNIQUE KEY `unq_depa_descri` (`depa_descri`) COMMENT 'No permite repetir el nombre de un departamento',
  UNIQUE KEY `unq_depa_cod_dane` (`depa_cod_dane`) COMMENT 'Llave Unica depa_cod_dane en def_Departamentos',
  KEY `def_depa_def_pais_fk` (`depa_pais`) COMMENT 'Llave foranea de departamentos hacia un pais',
  CONSTRAINT `def_depa_def_pais_fk` FOREIGN KEY (`depa_pais`) REFERENCES `def_paises` (`pais_pais`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `def_departamentos` */

insert  into `def_departamentos`(`depa_depa`,`depa_cod_dane`,`depa_pais`,`depa_descri`,`depa_estado`,`depa_usuains`,`depa_fecins`,`depa_usuaupd`,`depa_fechaupd`) values 
(5,'01',8,'ATLANTICO',1,'','0000-00-00',NULL,NULL),
(20,NULL,8,'MAGDALENA',1,NULL,NULL,NULL,NULL);

/*Table structure for table `def_escuelas` */

DROP TABLE IF EXISTS `def_escuelas`;

CREATE TABLE `def_escuelas` (
  `escu_escu` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria autoincrementable de las escuelas',
  `escu_descri` varchar(100) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Nombres de las escuelas',
  `escu_estado` tinyint(1) NOT NULL COMMENT 'Estado de las escuelas',
  `escu_fecins` date DEFAULT NULL COMMENT 'fecha de inserci',
  `escu_usuains` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'usuario de inserci',
  `escu_fecupd` date DEFAULT NULL COMMENT 'fecha de actualizaci',
  `escu_insupd` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'usuario de actualizaci',
  `escu_muni` int(11) NOT NULL COMMENT 'Municipio Fk',
  PRIMARY KEY (`escu_escu`),
  KEY `def_escu_def_muni_fk` (`escu_muni`),
  CONSTRAINT `def_escu_def_muni_fk` FOREIGN KEY (`escu_muni`) REFERENCES `def_municipios` (`muni_muni`)
) ENGINE=InnoDB AUTO_INCREMENT=155 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `def_escuelas` */

insert  into `def_escuelas`(`escu_escu`,`escu_descri`,`escu_estado`,`escu_fecins`,`escu_usuains`,`escu_fecupd`,`escu_insupd`,`escu_muni`) values 
(1,'CENTRO DEEDUCACION BASICA# 201',1,NULL,NULL,NULL,NULL,2),
(2,'ESCUELA NORMALSUPERIOR DEL DISTRITO DE BARRANQUILLA',1,NULL,NULL,NULL,NULL,2),
(3,'ESCUELA NORMALSUPERIOR LAHACIENDA',1,NULL,NULL,NULL,NULL,2),
(4,'INSTITUCION EDUCATIVA COMUNITARIA DISTRITAL MANUEL ELKIN PATARROYO',1,NULL,NULL,NULL,NULL,2),
(5,'INSTITUCION EDUCATIVA DISTRITAL # 103 ',1,NULL,NULL,NULL,NULL,2),
(6,'INSTITUCION EDUCATIVA DISTRITAL ALEXANDER VON HUMBOLDT',1,NULL,NULL,NULL,NULL,2),
(7,'INSTITUCION EDUCATIVA DISTRITAL ALFONSO LOPEZ ',1,NULL,NULL,NULL,NULL,2),
(8,'INSTITUCION EDUCATIVA DISTRITAL ALFREDO CORREA DE ANDREIS',1,NULL,NULL,NULL,NULL,2),
(9,'INSTITUCIÓN EDUCATIVA DISTRITAL ANTONIO JOSE DE SUCRE ',1,NULL,NULL,NULL,NULL,2),
(10,'INSTITUCION EDUCATIVA DISTRITAL BETANIA NORTE ',1,NULL,NULL,NULL,NULL,2),
(11,'INSTITUCION EDUCATIVA DISTRITAL BETZABE ESPINOSA',1,NULL,NULL,NULL,NULL,2),
(12,'INSTITUCION EDUCATIVA DISTRITAL BOSTON ',1,NULL,NULL,NULL,NULL,2),
(13,'INSTITUCION EDUCATIVA DISTRITAL BRISAS DISTRITAL BRISAS ',1,NULL,NULL,NULL,NULL,2),
(14,'INSTITUCION EDUCATIVA DISTRITAL BUENOS DISTRITAL BUENOS AIRES ',1,NULL,NULL,NULL,NULL,2),
(15,'INSTITUCION EDUCATIVA DISTRITAL CALIXTO DISTRITAL CALIXTO ALVAREZ ',1,NULL,NULL,NULL,NULL,2),
(16,'INSTITUCION EDUCATIVA DISTRITAL CAMILO DISTRITAL CAMILO TORRES TENORIO ',1,NULL,NULL,NULL,NULL,2),
(17,'INSTITUCION EDUCATIVA DISTRITAL CARLOS DISTRITAL CARLOS MEISEL ',1,NULL,NULL,NULL,NULL,2),
(18,'INSTITUCION EDUCATIVA DISTRITAL DISTRITAL CIUDADELA 20 DE JULIO ',1,NULL,NULL,NULL,NULL,2),
(19,'INSTITUCION EDUCATIVA DISTRITAL DISTRITAL CIUDADELA ESTUDIANTIL ',1,NULL,NULL,NULL,NULL,2),
(20,'INSTITUCION EDUCATIVA DISTRITAL CIVICA 7 DISTRITAL CIVICA 7 DE ABRIL ',1,NULL,NULL,NULL,NULL,2),
(21,'INSTITUCION EDUCATIVA DISTRITAL DISTRITAL COMUNITARIA METROPOLITANA ',1,NULL,NULL,NULL,NULL,2),
(22,'INSTITUCION EDUCATIVA DISTRITAL COMUNITARIA OCTAVIO PAZ',1,NULL,NULL,NULL,NULL,2),
(23,'INSTITUCION EDUCATIVA DISTRITAL COMUNITARIA SIETE DE ABRIL',1,NULL,NULL,NULL,NULL,2),
(24,'INSTITUCION EDUCATIVA DISTRITAL CONCENTRACION CEVILLAR',1,NULL,NULL,NULL,NULL,2),
(25,'INSTITUCION EDUCATIVA DISTRITAL COSTA CARIBE',1,NULL,NULL,NULL,NULL,2),
(26,'INSTITUCION EDUCATIVA DISTRITAL CULTURAL LAS MALVINAS',1,NULL,NULL,NULL,NULL,2),
(27,'INSTITUCIÓN EDUCATIVA DISTRITAL DAVID SANCHEZ JULIAO',1,NULL,NULL,NULL,NULL,2),
(28,'INSTITUCION EDUCATIVA DISTRITAL DE ARTE Y CULTURA ALEJANDRO OBREGON',1,NULL,NULL,NULL,NULL,2),
(29,'INSTITUCION EDUCATIVA DISTRITAL DE BARRANQUILLA CODEBA',1,NULL,NULL,NULL,NULL,2),
(30,'INSTITUCION EDUCATIVA DISTRITAL DE CARRIZAL',1,NULL,NULL,NULL,NULL,2),
(31,'INSTITUCION EDUCATIVA DISTRITAL DE EXPERIENCIAS PEDAGOGICAS',1,NULL,NULL,NULL,NULL,2),
(32,'INSTITUCION EDUCATIVA DISTRITAL DE FORMACION INTEGRAL',1,NULL,NULL,NULL,NULL,2),
(33,'INSTITUCION EDUCATIVA DISTRITAL DE FORMACION TECNICA DIVERSIFICADA ALBERTO ASSA',1,NULL,NULL,NULL,NULL,2),
(34,'INSTITUCION EDUCATIVA DISTRITAL DE LAS NIEVES',1,NULL,NULL,NULL,NULL,2),
(35,'INSTITUCION EDUCATIVA DISTRITAL DEL BARRIO MONTES',1,NULL,NULL,NULL,NULL,2),
(36,'INSTITUCION EDUCATIVA DISTRITAL DEL BARRIO SIMON BOLIVAR',1,NULL,NULL,NULL,NULL,2),
(37,'INSTITUCION EDUCATIVA DISTRITAL DEL CARIBE',1,NULL,NULL,NULL,NULL,2),
(38,'INSTITUCION EDUCATIVA DISTRITAL DEL DESARROLLO HUMANO Y CULTURAL DEL CARIBE',1,NULL,NULL,NULL,NULL,2),
(39,'INSTITUCION EDUCATIVA DISTRITAL DENIS HERRERA DE VILLA',1,NULL,NULL,NULL,NULL,2),
(40,'INSTITUCION EDUCATIVA DISTRITAL DESPERTAR DEL SUR',1,NULL,NULL,NULL,NULL,2),
(41,'INSTITUCION EDUCATIVA DISTRITAL EDUARDO SANTOS',1,NULL,NULL,NULL,NULL,2),
(42,'INSTITUCION EDUCATIVA DISTRITAL EL CAMPITO',1,NULL,NULL,NULL,NULL,2),
(43,'INSTITUCION EDUCATIVA DISTRITAL EL CAÑAHUATE',1,NULL,NULL,NULL,NULL,2),
(44,'INSTITUCION EDUCATIVA DISTRITAL EL CASTILLO DE LA ALBORAYA',1,NULL,NULL,NULL,NULL,2),
(45,'INSTITUCION EDUCATIVA DISTRITAL EL CORAZON DEL SANTUARIO',1,NULL,NULL,NULL,NULL,2),
(46,'INSTITUCION EDUCATIVA DISTRITAL EL PARAISO',1,NULL,NULL,NULL,NULL,2),
(47,'INSTITUCION EDUCATIVA DISTRITAL EL PUEBLO',1,NULL,NULL,NULL,NULL,2),
(48,'INSTITUCION EDUCATIVA DISTRITAL EL SILENCIO',1,NULL,NULL,NULL,NULL,2),
(49,'INSTITUCION EDUCATIVA DISTRITAL EL VALLE',1,NULL,NULL,NULL,NULL,2),
(50,'INSTITUCION EDUCATIVA DISTRITAL ESTER FORERO',1,NULL,NULL,NULL,NULL,2),
(51,'INSTITUCION EDUCATIVA DISTRITAL ETNOEDUCATIVO PAULINO SALGADO BATATA',1,NULL,NULL,NULL,NULL,2),
(52,'INSTITUCION EDUCATIVA DISTRITAL EUSEBIO CARO',1,NULL,NULL,NULL,NULL,2),
(53,'INSTITUCION EDUCATIVA DISTRITAL EVARDO TURIZO PALENCIA',1,NULL,NULL,NULL,NULL,2),
(54,'INSTITUCION EDUCATIVA DISTRITAL EVARISTO SOURDIS',1,NULL,NULL,NULL,NULL,2),
(55,'INSTITUCION EDUCATIVA DISTRITAL FUNDACION PIES DESCALZOS',1,NULL,NULL,NULL,NULL,2),
(56,'INSTITUCION EDUCATIVA DISTRITAL GABRIEL GARCIA MARQUEZ',1,NULL,NULL,NULL,NULL,2),
(57,'INSTITUCION EDUCATIVA DISTRITAL GOLDA MEIR',1,NULL,NULL,NULL,NULL,2),
(58,'INSTITUCION EDUCATIVA DISTRITAL HILDA MUÑOZ',1,NULL,NULL,NULL,NULL,2),
(59,'INSTITUCION EDUCATIVA DISTRITAL HOGAR MARIANO',1,NULL,NULL,NULL,NULL,2),
(60,'INSTITUCION EDUCATIVA DISTRITAL INMACULADA CONCEPCION',1,NULL,NULL,NULL,NULL,2),
(61,'INSTITUCION EDUCATIVA DISTRITAL INOCENCIO CHINCA',1,NULL,NULL,NULL,NULL,2),
(62,'INSTITUCION EDUCATIVA DISTRITAL INSTITUTO TECNICO DE COMERCIO BARRANQUILLA',1,NULL,NULL,NULL,NULL,2),
(63,'INSTITUCION EDUCATIVA DISTRITAL ISAAC NEWTON',1,NULL,NULL,NULL,NULL,2),
(64,'INSTITUCION EDUCATIVA DISTRITAL JAVIER SANCHEZ',1,NULL,NULL,NULL,NULL,2),
(65,'INSTITUCION EDUCATIVA DISTRITAL JESUS DE NAZARETH',1,NULL,NULL,NULL,NULL,2),
(66,'INSTITUCION EDUCATIVA DISTRITAL JESUS MISERICORDIOSO',1,NULL,NULL,NULL,NULL,2),
(67,'INSTITUCION EDUCATIVA DISTRITAL JORGE ISAAC',1,NULL,NULL,NULL,NULL,2),
(68,'INSTITUCION EDUCATIVA DISTRITAL JORGE ROBLEDO ORTIZ',1,NULL,NULL,NULL,NULL,2),
(69,'INSTITUCION EDUCATIVA DISTRITAL JOSE ANTONIO GALAN',1,NULL,NULL,NULL,NULL,2),
(70,'INSTITUCION EDUCATIVA DISTRITAL JOSE CONSUEGRA HIGGINS',1,NULL,NULL,NULL,NULL,2),
(71,'INSTITUCION EDUCATIVA DISTRITAL JOSE MARIA VELAZ',1,NULL,NULL,NULL,NULL,2),
(72,'INSTITUCION EDUCATIVA DISTRITAL JOSE MARTI',1,NULL,NULL,NULL,NULL,2),
(73,'INSTITUCION EDUCATIVA DISTRITAL JUAN ACOSTA SOLERA',1,NULL,NULL,NULL,NULL,2),
(74,'INSTITUCION EDUCATIVA DISTRITAL JUAN JOSE RONDON',1,NULL,NULL,NULL,NULL,2),
(75,'INSTITUCION EDUCATIVA DISTRITAL KARL PARRISH',1,NULL,NULL,NULL,NULL,2),
(76,'INSTITUCION EDUCATIVA DISTRITAL LA CONCEPCION',1,NULL,NULL,NULL,NULL,2),
(77,'INSTITUCION EDUCATIVA DISTRITAL LA ESMERALDA',1,NULL,NULL,NULL,NULL,2),
(78,'INSTITUCION EDUCATIVA DISTRITAL LA ESPERANZA DEL SUR',1,NULL,NULL,NULL,NULL,2),
(79,'INSTITUCION EDUCATIVA DISTRITAL LA LIBERTAD',1,NULL,NULL,NULL,NULL,2),
(80,'INSTITUCION EDUCATIVA DISTRITAL LA LUZ',1,NULL,NULL,NULL,NULL,2),
(81,'INSTITUCION EDUCATIVA DISTRITAL LA MAGDALENA',1,NULL,NULL,NULL,NULL,2),
(82,'INSTITUCION EDUCATIVA DISTRITAL LA MERCED',1,NULL,NULL,NULL,NULL,2),
(83,'INSTITUCION EDUCATIVA DISTRITAL LA MILAGROSA FE Y ALEGRIA',1,NULL,NULL,NULL,NULL,2),
(84,'INSTITUCION EDUCATIVA DISTRITAL LA PRESENTACION',1,NULL,NULL,NULL,NULL,2),
(85,'INSTITUCION EDUCATIVA DISTRITAL LA SALLE',1,NULL,NULL,NULL,NULL,2),
(86,'INSTITUCION EDUCATIVA DISTRITAL LA UNION',1,NULL,NULL,NULL,NULL,2),
(87,'INSTITUCION EDUCATIVA DISTRITAL LA VICTORIA',1,NULL,NULL,NULL,NULL,2),
(88,'INSTITUCION EDUCATIVA DISTRITAL LAS AMERICAS',1,NULL,NULL,NULL,NULL,2),
(89,'INSTITUCION EDUCATIVA DISTRITAL LAS FLORES',1,NULL,NULL,NULL,NULL,2),
(90,'INSTITUCION EDUCATIVA DISTRITAL LAS GARDENIAS',1,NULL,NULL,NULL,NULL,2),
(91,'INSTITUCION EDUCATIVA DISTRITAL LAS GRANJAS',1,NULL,NULL,NULL,NULL,2),
(92,'INSTITUCION EDUCATIVA DISTRITAL LAS MERCEDES SAN PABLO',1,NULL,NULL,NULL,NULL,2),
(93,'INSTITUCION EDUCATIVA DISTRITAL LESTONNAC',1,NULL,NULL,NULL,NULL,2),
(94,'INSTITUCION EDUCATIVA DISTRITAL LOS LAURELES',1,NULL,NULL,NULL,NULL,2),
(95,'INSTITUCION EDUCATIVA DISTRITAL LOS ROSALES',1,NULL,NULL,NULL,NULL,2),
(96,'INSTITUCION EDUCATIVA DISTRITAL LUIS CARLOS GALAN SARMIENTO',1,NULL,NULL,NULL,NULL,2),
(97,'INSTITUCION EDUCATIVA DISTRITAL LUZ DEL CARIBE',1,NULL,NULL,NULL,NULL,2),
(98,'INSTITUCION EDUCATIVA DISTRITAL MADRE MARCELINA',1,NULL,NULL,NULL,NULL,2),
(99,'INSTITUCION EDUCATIVA DISTRITAL MADRES CATOLICAS',1,NULL,NULL,NULL,NULL,2),
(100,'INSTITUCION EDUCATIVA DISTRITAL MANUEL ZAPATA OLIVELLA',1,NULL,NULL,NULL,NULL,2),
(101,'INSTITUCION EDUCATIVA DISTRITAL MARCO FIDEL SUAREZ',1,NULL,NULL,NULL,NULL,2),
(102,'INSTITUCION EDUCATIVA DISTRITAL MARIA AUXILIADORA',1,NULL,NULL,NULL,NULL,2),
(103,'INSTITUCION EDUCATIVA DISTRITAL MARIA INMACULADA',1,NULL,NULL,NULL,NULL,2),
(104,'INSTITUCION EDUCATIVA DISTRITAL MARIE POUSSEPIN',1,NULL,NULL,NULL,NULL,2),
(105,'INSTITUCION EDUCATIVA DISTRITAL MAYOR DE BARRANQUILLA Y DEL CARIBE',1,NULL,NULL,NULL,NULL,2),
(106,'INSTITUCION EDUCATIVA DISTRITAL MIGUEL ANGEL BUILES',1,NULL,NULL,NULL,NULL,2),
(107,'INSTITUCION EDUCATIVA DISTRITAL MUNDO BOLIVARIANO',1,NULL,NULL,NULL,NULL,2),
(108,'INSTITUCION EDUCATIVA DISTRITAL MURILLO',1,NULL,NULL,NULL,NULL,2),
(109,'INSTITUCION EDUCATIVA DISTRITAL NIÑOS JESUS',1,NULL,NULL,NULL,NULL,2),
(110,'INSTITUCION EDUCATIVA DISTRITAL NO. 161',1,NULL,NULL,NULL,NULL,2),
(111,'INSTITUCION EDUCATIVA DISTRITAL NO. 176 INSTITUCION',1,NULL,NULL,NULL,NULL,2),
(112,'INSTITUCION EDUCATIVA DISTRITAL NUESTRA SEÑORA DE LAS NIEVES',1,NULL,NULL,NULL,NULL,2),
(113,'INSTITUCION EDUCATIVA DISTRITAL NUESTRA SEÑORA DEL ROSARIO',1,NULL,NULL,NULL,NULL,2),
(114,'INSTITUCION EDUCATIVA DISTRITAL NUEVA GRANADA',1,NULL,NULL,NULL,NULL,2),
(115,'INSTITUCION EDUCATIVA DISTRITAL NUEVO BOSQUE',1,NULL,NULL,NULL,NULL,2),
(116,'INSTITUCION EDUCATIVA DISTRITAL OLAYA',1,NULL,NULL,NULL,NULL,2),
(117,'INSTITUCION EDUCATIVA DISTRITAL PARA EL DESARROLLO DEL TALENTO HUMANO',1,NULL,NULL,NULL,NULL,2),
(118,'INSTITUCION EDUCATIVA DISTRITAL PARA EL DESARROLLO HUMANO MARIA CANO',1,NULL,NULL,NULL,NULL,2),
(119,'INSTITUCION EDUCATIVA DISTRITAL PESTALOZZI',1,NULL,NULL,NULL,NULL,2),
(120,'INSTITUCION EDUCATIVA DISTRITAL REUVEN FEUERSTEN',1,NULL,NULL,NULL,NULL,2),
(121,'INSTITUCION EDUCATIVA DISTRITAL RODOLFO LLINAS RIASCOS',1,NULL,NULL,NULL,NULL,2),
(122,'INSTITUCION EDUCATIVA DISTRITAL SAGRADO CORAZON DE JESUS',1,NULL,NULL,NULL,NULL,2),
(123,'INSTITUCIÓN EDUCATIVA DISTRITAL SALVADOR ENTREGAS',1,NULL,NULL,NULL,NULL,2),
(124,'INSTITUCION EDUCATIVA DISTRITAL SALVADOR SUAREZ SUAREZ',1,NULL,NULL,NULL,NULL,2),
(125,'INSTITUCION EDUCATIVA DISTRITAL SAN GABRIEL',1,NULL,NULL,NULL,NULL,2),
(126,'INSTITUCION EDUCATIVA DISTRITAL SAN JOSE',1,NULL,NULL,NULL,NULL,2),
(127,'INSTITUCION EDUCATIVA DISTRITAL SAN LUIS',1,NULL,NULL,NULL,NULL,2),
(128,'INSTITUCION EDUCATIVA DISTRITAL SAN\r\nMIGUEL ARCANGEL',1,NULL,NULL,NULL,NULL,2),
(129,'INSTITUCION EDUCATIVA DISTRITAL SAN SALVADOR',1,NULL,NULL,NULL,NULL,2),
(130,'INSTITUCION EDUCATIVA DISTRITAL SAN VICENTE DE PAUL',1,NULL,NULL,NULL,NULL,2),
(131,'INSTITUCION EDUCATIVA DISTRITAL SANTA BERNARDITA',1,NULL,NULL,NULL,NULL,2),
(132,'INSTITUCION EDUCATIVA DISTRITAL SANTA MAGDALENA SOFIA',1,NULL,NULL,NULL,NULL,2),
(133,'INSTITUCION EDUCATIVA DISTRITAL SANTA MARIA',1,NULL,NULL,NULL,NULL,2),
(134,'INSTITUCION EDUCATIVA DISTRITAL SANTO DOMINGO DE GUZMAN',1,NULL,NULL,NULL,NULL,2),
(135,'INSTITUCION EDUCATIVA DISTRITAL SARID ARTETA DE VASQUEZ',1,NULL,NULL,NULL,NULL,2),
(136,'INSTITUCION EDUCATIVA DISTRITAL SIMON BOLIVAR',1,NULL,NULL,NULL,NULL,2),
(137,'INSTITUCION EDUCATIVA DISTRITAL SOFIA CAMARGO DE LLERAS',1,NULL,NULL,NULL,NULL,2),
(138,'INSTITUCION EDUCATIVA DISTRITAL SONIA AHUMADA',1,NULL,NULL,NULL,NULL,2),
(139,'INSTITUCION EDUCATIVA DISTRITAL TECNICA BILINGUE JORGE \r\nNICOLAS ABELLO',1,NULL,NULL,NULL,NULL,2),
(140,'INSTITUCION EDUCATIVA DISTRITAL TECNICA CRUZADA SOCIAL',1,NULL,NULL,NULL,NULL,2),
(141,'INSTITUCION EDUCATIVA DISTRITAL TECNICA DE REBOLO',1,NULL,NULL,NULL,NULL,2),
(142,'INSTITUCION EDUCATIVA DISTRITAL TECNICA DIVERSIFICADA DE BARRANQUILLA COTEDIBA',1,NULL,NULL,NULL,NULL,2),
(143,'INSTITUCION EDUCATIVA DISTRITAL TECNICA HELENA DE CHAUVIN',1,NULL,NULL,NULL,NULL,2),
(144,'INSTITUCION EDUCATIVA DISTRITAL TECNICA MEIRA DEL MAR',1,NULL,NULL,NULL,NULL,2),
(145,'INSTITUCION EDUCATIVA DISTRITAL TECNICA METROPOLITANO DE BARRANQUILLA PARQUE EDUCATIVO',1,NULL,NULL,NULL,NULL,2),
(146,'INSTITUCION EDUCATIVA DISTRITAL TÉCNICA NACIONAL DE COMERCIO',1,NULL,NULL,NULL,NULL,2),
(147,'INSTITUCION EDUCATIVA DISTRITAL TECNICA PABLO NERUDA',1,NULL,NULL,NULL,NULL,2),
(148,'INSTITUCION EDUCATIVA DISTRITAL TECNICO EL SANTUARIO',1,NULL,NULL,NULL,NULL,2),
(149,'INSTITUCION EDUCATIVA DISTRITAL TECNICO JESUS MAESTRO',1,NULL,NULL,NULL,NULL,2),
(150,'INSTITUCION EDUCATIVA DISTRITAL TIERRA SANTA',1,NULL,NULL,NULL,NULL,2),
(151,'INSTITUCION EDUCATIVA DISTRITAL UNIVERSAL',1,NULL,NULL,NULL,NULL,2),
(152,'INSTITUCION EDUCATIVA DISTRITAL VILLA DEL CARMEN',1,NULL,NULL,NULL,NULL,2),
(153,'INSTITUCION EDUCATIVA DISTRITAL VILLANUEVA',1,NULL,NULL,NULL,NULL,2),
(154,'INSTITUCION EDUCATIVA DISTRITAL VILLAS DE SAN PABLO',1,NULL,NULL,NULL,NULL,2);

/*Table structure for table `def_municipios` */

DROP TABLE IF EXISTS `def_municipios`;

CREATE TABLE `def_municipios` (
  `muni_muni` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria autoincrementable de los municipios',
  `muni_depa` int(11) NOT NULL COMMENT 'Departamento al que pertenece el municipio',
  `muni_cod_dane` varchar(10) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Codigo Dane del municipio',
  `muni_descri` varchar(50) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Descripci',
  `muni_estado` tinyint(1) DEFAULT 1 COMMENT 'Estado del Municipio A Activo I Inactivo',
  `muni_usuains` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario que inserta',
  `muni_fecins` date DEFAULT NULL COMMENT 'Fecha de inserci',
  `muni_usuaupd` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario de actualizaci',
  `muni_fecupd` date DEFAULT NULL COMMENT 'Fecha de actualizaci',
  PRIMARY KEY (`muni_muni`) COMMENT 'Llave primaria de los municipios',
  UNIQUE KEY `def_muni_descri_unq` (`muni_descri`,`muni_depa`) COMMENT 'No permite depetir dos veces el nombre de un municipio para un departamento',
  UNIQUE KEY `def_muni_cod_dane_unq` (`muni_cod_dane`) COMMENT 'Llave unica codigo dane de los municipios',
  KEY `def_muni_def_depa_fk` (`muni_depa`),
  CONSTRAINT `def_muni_def_depa_fk` FOREIGN KEY (`muni_depa`) REFERENCES `def_departamentos` (`depa_depa`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `def_municipios` */

insert  into `def_municipios`(`muni_muni`,`muni_depa`,`muni_cod_dane`,`muni_descri`,`muni_estado`,`muni_usuains`,`muni_fecins`,`muni_usuaupd`,`muni_fecupd`) values 
(2,5,NULL,'BARRANQUILLA',1,NULL,NULL,NULL,NULL),
(4,5,NULL,'SOLEDAD',1,NULL,NULL,NULL,NULL);

/*Table structure for table `def_paises` */

DROP TABLE IF EXISTS `def_paises`;

CREATE TABLE `def_paises` (
  `pais_pais` int(11) NOT NULL AUTO_INCREMENT COMMENT 'LLave unica autoincrementable de la tabla paises',
  `pais_descri` varchar(30) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Descripci',
  `pais_estado` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Estado del Pais',
  `pais_usuains` varchar(20) COLLATE utf8_spanish2_ci DEFAULT 'user' COMMENT 'Usuario que inserta pais',
  `pais_fecins` date DEFAULT NULL COMMENT 'Fecha de inserci',
  `pais_usuaupd` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario que actualiza un pa',
  `pais_fecupd` date DEFAULT NULL COMMENT 'Fecha en que se actualiza un pa',
  PRIMARY KEY (`pais_pais`) COMMENT 'LLave primaria de la tabla def_paises',
  UNIQUE KEY `unq_def_pai_descri` (`pais_descri`) COMMENT 'LLave que evita que se pueda repetir el nombre de un pa'
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `def_paises` */

insert  into `def_paises`(`pais_pais`,`pais_descri`,`pais_estado`,`pais_usuains`,`pais_fecins`,`pais_usuaupd`,`pais_fecupd`) values 
(8,'COLOMBIA',1,'user',NULL,NULL,NULL);

/*Table structure for table `vot_lideres` */

DROP TABLE IF EXISTS `vot_lideres`;

CREATE TABLE `vot_lideres` (
  `lide_lide` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria de los lideres',
  `lide_tipo_id` enum('CC') COLLATE utf8_spanish2_ci NOT NULL DEFAULT 'CC' COMMENT 'Tipo de identificaci',
  `lide_id` int(20) NOT NULL COMMENT 'Numero de identificaci',
  `lide_pri_nombre` varchar(20) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Primer nombre',
  `lide_seg_nombre` varchar(20) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Segundo nombre',
  `lide_pri_apellido` varchar(20) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Primer apellido',
  `lide_seg_apellido` varchar(20) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Segundo apellido',
  `lide_direccion` varchar(100) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Direccion',
  `lide_telefono` int(20) DEFAULT NULL COMMENT 'Telefono',
  `lide_celular` int(20) DEFAULT NULL COMMENT 'Celular',
  `lide_estado` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Estado del lider',
  `lide_usuains` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario inserta',
  `lide_fecins` date DEFAULT NULL COMMENT 'Fecha inserta',
  `lide_usuaupd` varchar(20) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Usuario actualiza',
  `lide_fecupd` date DEFAULT NULL COMMENT 'Fecha actualiza',
  PRIMARY KEY (`lide_lide`),
  UNIQUE KEY `vot_lide_id_unq` (`lide_tipo_id`,`lide_id`) COMMENT 'No permite que hayan dos lideres con igual numero de identificaci'
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `vot_lideres` */

insert  into `vot_lideres`(`lide_lide`,`lide_tipo_id`,`lide_id`,`lide_pri_nombre`,`lide_seg_nombre`,`lide_pri_apellido`,`lide_seg_apellido`,`lide_direccion`,`lide_telefono`,`lide_celular`,`lide_estado`,`lide_usuains`,`lide_fecins`,`lide_usuaupd`,`lide_fecupd`) values 
(21,'CC',0,'','','','',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL),
(22,'CC',123456789,'jojiojo','oijoj','oijoij','oijoij','luojio',1651651,2147483647,1,NULL,NULL,NULL,NULL);

/*Table structure for table `vot_predi_votos` */

DROP TABLE IF EXISTS `vot_predi_votos`;

CREATE TABLE `vot_predi_votos` (
  `prvo_prvo` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria autoincrementable prediccion votos',
  `prvo_tipo_id` enum('CC') COLLATE utf8_spanish2_ci NOT NULL DEFAULT 'CC' COMMENT 'tipo de identificacion del votante',
  `prvo_id` varchar(20) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Identificacion del votante',
  `prvo_pri_nombre` varchar(50) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Primer nombre votante',
  `prvo_seg_nombre` varchar(50) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Segundo nombre votante',
  `prvo_pri_apellido` varchar(50) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Primer apellido votante',
  `prvo_seg_apellido` varchar(50) COLLATE utf8_spanish2_ci NOT NULL COMMENT 'Segundo apellido votante',
  `prvo_telefono` int(20) DEFAULT NULL COMMENT 'Telefono del votante',
  `prvo_direccion` varchar(100) COLLATE utf8_spanish2_ci DEFAULT NULL COMMENT 'Direcci',
  `prvo_escu` int(11) NOT NULL COMMENT 'Escuela de votaci',
  `prvo_mesa` int(10) NOT NULL COMMENT 'Mesa de votaci',
  `prvo_vigencia` int(4) NOT NULL COMMENT 'vigencia de la votaci',
  `prvo_lide` int(11) NOT NULL COMMENT 'Llave foranea del lider que esta registrando los votos',
  `prvo_estado` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Estado del registrado',
  PRIMARY KEY (`prvo_prvo`),
  UNIQUE KEY `vot_predi_votos_vot_unq` (`prvo_id`,`prvo_vigencia`) COMMENT 'Un votante no puede registrar 2 votos en una misma vigencia',
  KEY `vot_predi_votos_def_escuelas_fk` (`prvo_escu`),
  KEY `vot_predi_votos_vot_lideres_fk` (`prvo_lide`),
  CONSTRAINT `vot_predi_votos_def_escuelas_fk` FOREIGN KEY (`prvo_escu`) REFERENCES `def_escuelas` (`escu_escu`),
  CONSTRAINT `vot_predi_votos_vot_lideres_fk` FOREIGN KEY (`prvo_lide`) REFERENCES `vot_lideres` (`lide_lide`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

/*Data for the table `vot_predi_votos` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
